---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      headlamp:
        pod:
          automountServiceAccountToken: true
        serviceAccount:
          identifier: headlamp
        containers:
          app:
            image:
              repository: ghcr.io/headlamp-k8s/headlamp
              tag: v0.42.0
            args:
              - -in-cluster
              - -kubeconfig=/home/headlamp/.kube/config
            env:
              KUBECONFIG: /home/headlamp/.kube/config
    serviceAccount:
      headlamp:
        forceRename: headlamp
    service:
      app:
        controller: headlamp
        ports:
          http:
            port: 4466
    persistence:
      kubeconfig:
        type: configMap
        name: headlamp-kubeconfig
        globalMounts:
          - path: /home/headlamp/.kube
    ingress:
      app:
        enabled: false
