# rbac/node-volumeattachment-get.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-get-volumeattachment
rules:
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "watch", "list"]   # watch/list lets kubelet stream updates
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-get-volumeattachment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-get-volumeattachment
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
