apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-secret-reader
  namespace: kube-prometheus-stack
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - prometheus-kube-prometheus-stack
      - prometheus-kube-prometheus-stack-web-config
      - prometheus-kube-prometheus-stack-tls-assets-0
    verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-secret-reader-binding
  namespace: kube-prometheus-stack
subjects:
  - kind: ServiceAccount
    name: prometheus-kube-prometheus-stack
    namespace: kube-prometheus-stack
roleRef:
  kind: Role
  name: prometheus-secret-reader
  apiGroup: rbac.authorization.k8s.io
