apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic-paperless-data
  namespace: paperless
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${HETZNER_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${HETZNER_SECRET_KEY}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  RESTIC_REPOSITORY: s3:https://${HETZNER_S3_BUCKET_ENDPOINT}/${HETZNER_S3_BUCKET_NAME}/volsync/paperless/paperless-data
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: paperless-data
  namespace: paperless
spec:
  sourcePVC: paperless-data-nfs-pvc
  trigger:
    schedule: "32 3 * * *"
  restic:
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
    repository: volsync-restic-paperless-data
    copyMethod: Direct
    # Force a direct-attached cache PVC instead of an RWX share-manager path.
    cacheStorageClassName: longhorn
    cacheAccessModes:
      - ReadWriteOnce
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
