apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab
  namespace: metallb
spec:
  ipAddressPools:
    - homelab
  nodeSelectors:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k8s-control-1
            - k8s-control-2
            - k8s-control-3
            - k8s-gpu-1
            - k8s-worker-1
            - k8s-worker-2
