apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-dind
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
