apiVersion: v1
kind: Secret
metadata:
  name: hetzner-s3
  namespace: etcd-backup
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${HETZNER_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${HETZNER_SECRET_KEY}
  AWS_ENDPOINT: https://${HETZNER_S3_BUCKET_ENDPOINT}
