apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-credentials.secret.yaml
  - cluster.yaml
  - scheduled-backup.yaml
  - cnpg-restore-drill.yaml
  - networkpolicy.yaml
