apiVersion: v1
kind: Secret
metadata:
  name: hetzner-s3
  namespace: authentik
type: Opaque
stringData:
  accessKey: ${HETZNER_ACCESS_KEY}
  secretKey: ${HETZNER_SECRET_KEY}
  encrKey: ${VOLSYNC_RESTIC_PASSWORD}
