apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headlamp/ks.yaml
  - authentik/ks.yaml
  - authentik-ldap-outpost/ks.yaml
  - vscode/ks.yaml
  - custom-app/ks.yaml
  - custom-app-postgres/ks.yaml
  - vaultwarden/ks.yaml
  - obsidian/ks.yaml
  - homepage/ks.yaml
  - gatus/ks.yaml
  - forgejo/ks.yaml
  - paperless/ks.yaml
  - nextcloud/ks.yaml
  - collabora/ks.yaml
  - silverbullet/ks.yaml
