apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - apiserver-egress-host.ccnp.yaml
  - etcd-backup-default-deny.yaml
  - etcd-backup-allow-dns.yaml
  - etcd-backup-allow-egress.yaml
  - arc-system-baseline.yaml
  - apps-baseline.yaml
  - apps-homepage-allow-ingress-cilium-gateway.cnp.yaml
  - apps-homepage-allow-ingress-gatus-internal.cnp.yaml
  - headlamp-baseline.yaml
  - headlamp-allow-ingress-cilium-gateway.cnp.yaml
  - headlamp-allow-ingress-gatus-internal.cnp.yaml
  - vscode-baseline.yaml
  - vscode-allow-ingress-cilium-gateway.cnp.yaml
  - vscode-allow-ingress-gatus-internal.cnp.yaml
  - authentik-baseline.yaml
  - authentik-allow-ingress-cilium-gateway.cnp.yaml
  - authentik-allow-ingress-gatus-internal.cnp.yaml
  - blocky-baseline.yaml
  - blocky-allow-ingress-external-dns.cnp.yaml
  - goldilocks-baseline.yaml
  - vaultwarden-baseline.yaml
  - vaultwarden-allow-ingress-cilium-gateway.cnp.yaml
  - vaultwarden-allow-ingress-gatus-internal.cnp.yaml
  - registry-baseline.yaml
  - registry-allow-ingress-cilium-gateway.cnp.yaml
  - registry-allow-ingress-gatus-internal.cnp.yaml
  - registry-allow-ingress-nodeport.cnp.yaml
  - registry-allow-ingress-vscode.yaml
  - vscode-allow-egress-registry.yaml
  - obsidian-baseline.yaml
  - obsidian-allow-ingress-cilium-gateway.cnp.yaml
  - obsidian-allow-ingress-gatus-internal.cnp.yaml
  - cert-manager-baseline.yaml
  - cert-manager-allow-ingress-webhook.cnp.yaml
  - collabora-baseline.yaml
  - collabora-allow-ingress-cilium-gateway.cnp.yaml
  - kube-system-scoped-baseline.yaml
  - kube-system-scoped-allow-egress-kube-apiserver.cnp.yaml
  - kube-system-coredns-scoped.yaml
  - kube-system-coredns-scoped-allow-egress-kube-apiserver.cnp.yaml
  - kube-system-metrics-server-scoped.cnp.yaml
  - kube-system-cilium-operator-hostnetwork.cnp.yaml
  - kube-system-cilium-envoy-hostnetwork.cnp.yaml
  - kube-system-cilium-agent-hostnetwork.cnp.yaml
  - kube-prometheus-stack-baseline.yaml
  - kube-prometheus-stack-grafana-allow-ingress-gatus-internal.cnp.yaml
  - kube-prometheus-stack-prometheus-allow-ingress-gatus-internal.cnp.yaml
  - kube-prometheus-stack-alertmanager-allow-ingress-gatus-internal.cnp.yaml
  - longhorn-system-baseline.yaml
  - longhorn-system-allow-ingress-webhook.cnp.yaml
  - loki-baseline.yaml
  - metallb-controller-baseline.yaml
  - metallb-controller-allow-ingress-webhook.cnp.yaml
  - metallb-speaker-hostnetwork-canary.cnp.yaml
  - mosquitto-baseline.yaml
  - nextcloud-baseline.yaml
  - nextcloud-allow-ingress-cilium-gateway.cnp.yaml
  - nextcloud-allow-ingress-gatus-internal.cnp.yaml
  - openebs-baseline.yaml
  - omada-controller-baseline.yaml
  - omada-controller-allow-ingress-cilium-gateway.cnp.yaml
  - omada-controller-allow-ingress-gatus-internal.cnp.yaml
  - gatus-default-deny.yaml
  - gatus-allow-dns.yaml
  - gatus-allow-ingress-cilium-gateway.cnp.yaml
  - gatus-internal-allow-egress-core-services.cnp.yaml
  - paperless-baseline.yaml
  - paperless-allow-ingress-cilium-gateway.cnp.yaml
  - paperless-allow-ingress-gatus-internal.cnp.yaml
  - couchdb-allow-ingress-gatus-internal.cnp.yaml
  - couchdb-allow-ingress-obsidian-livesync-init.cnp.yaml
  - spegel-baseline.yaml
  - spegel-allow-ingress-node-registry.cnp.yaml
  - snapshot-controller-baseline.yaml
  - snapshot-controller-allow-ingress-webhook.cnp.yaml
  - system-upgrade-baseline.yaml
  - tailscale-baseline.yaml
  - vpa-baseline.yaml
  - vpa-allow-ingress-webhook.cnp.yaml
  - volsync-baseline.yaml
  - cloudnative-pg-baseline.yaml
  - gatus-allow-egress-cilium-gateway.cnp.yaml
  - gatus-allow-egress-web.yaml
