apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-arc-system.yaml
  - namespace-arc-runners.yaml
  - helm-release-controller.yaml
  - helm-release-runners.yaml
  - runner-ops-rbac.yaml
