---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - namespace.yaml
  - pvc.yaml
  - backup.yaml
  - secret.yaml
  - obsidian-livesync.secret.yaml
  - obsidian-livesync-init-job.yaml
  - gateway-api-routes.yaml
