apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api/ks.yaml

# Optional network services.
#  - tailscale/ks.yaml                # Private access overlay; needs auth key.
#  - omada-controller/ks.yaml         # Stateful network controller.
#  - mosquitto/ks.yaml                # MQTT broker example.
