apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: docker-registry
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - k8s-control-2
          - k8s-control-3
          - k8s-control-4
          - k8s-worker-gpu-1
          - k8s-worker-2
          - k8s-worker-3
  serviceSelector:
    matchLabels:
      app: docker-registry
      registry-role: lb
