apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic-registry-data
  namespace: registry
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${HETZNER_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${HETZNER_SECRET_KEY}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  RESTIC_REPOSITORY: s3:https://${HETZNER_S3_BUCKET_ENDPOINT}/${HETZNER_S3_BUCKET_NAME}/volsync/registry/registry-data
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: registry-data
  namespace: registry
spec:
  sourcePVC: registry-data
  trigger:
    schedule: "42 3 * * *"
  restic:
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
    repository: volsync-restic-registry-data
    copyMethod: Direct
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: registry-data-restore-drill
  namespace: registry
spec:
  trigger:
    schedule: "50 5 1 * *"
  restic:
    repository: volsync-restic-registry-data
    copyMethod: None
    cleanupTempPVC: true
    cleanupCachePVC: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    capacity: 20Gi
