apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gatewayclassconfig-cilium.yaml
  - gatewayclass-cilium.yaml
  - internal-gateway.yaml
  - cilium-lbippool.yaml
  - cilium-l2announcementpolicy.yaml
