apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-seven
  namespace: flux-system
spec:
  providerRef:
    name: discord-seven
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: OCIRepository
      name: "*"
    - kind: Bucket
      name: "*"

