apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic-omada-controller-data
  namespace: omada-controller
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${HETZNER_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${HETZNER_SECRET_KEY}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  RESTIC_REPOSITORY: s3:https://${HETZNER_S3_BUCKET_ENDPOINT}/${HETZNER_S3_BUCKET_NAME}/volsync/omada-controller/omada-controller-data
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: omada-controller-data
  namespace: omada-controller
spec:
  sourcePVC: omada-controller-data
  trigger:
    schedule: "02 4 * * 0"
  restic:
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
    repository: volsync-restic-omada-controller-data
    copyMethod: Snapshot
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic-omada-controller-work
  namespace: omada-controller
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${HETZNER_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${HETZNER_SECRET_KEY}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  RESTIC_REPOSITORY: s3:https://${HETZNER_S3_BUCKET_ENDPOINT}/${HETZNER_S3_BUCKET_NAME}/volsync/omada-controller/omada-controller-work
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: omada-controller-work
  namespace: omada-controller
spec:
  sourcePVC: omada-controller-work
  trigger:
    schedule: "12 4 * * 0"
  restic:
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
    repository: volsync-restic-omada-controller-work
    copyMethod: Snapshot
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 4
      monthly: 3
