apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - k8s-control-1
          - k8s-control-2
          - k8s-control-3
          - k8s-gpu-1
          - k8s-worker-1
          - k8s-worker-2
  serviceSelector:
    matchLabels:
      homelab.dev/lb-pool: homelab
