apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - crds/ipaddresspool-homelab.yaml
  - crds/l2advertisement-homelab.yaml
  - cilium-homelab-lbippool.yaml
  - cilium-homelab-l2announcementpolicy.yaml
