---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: obsidian-vaults-nfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: obsidian-vaults-nfs-pv
spec:
  storageClassName: obsidian-vaults-nfs
  capacity:
    storage: 1Mi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.${DOMAIN_HOST}
    path: /mnt/storage_layer/weave
  mountOptions:
    - nfsvers=4.1
    - hard
    - tcp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vaults-nfs-pvc
  namespace: obsidian
spec:
  storageClassName: obsidian-vaults-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Mi
