apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-config/ks.yaml

# Optional core services.
#  - clusterissuer/ks.yaml            # ACME issuer; needs DNS provider token.
#  - blocky/ks.yaml                   # DNS sinkhole/k8s_gateway example.
#  - system-upgrade-controller-plans/ks.yaml # Needs System Upgrade Controller.
