---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - vaultwarden-admin.secret.yaml
  - hetzner-s3-credentials.yaml
  - namespace.yaml
  - volsync-hetzner.yaml
  - cnpg-restore-drill.yaml
  - gateway-api-routes.yaml
